### ISSUE TITLE
PCODAR Meta Issue

### ISSUE THREAD

**Issue by ironmig** [uf-mil/NaviGator#339]
PCODAR is the point cloud object recognition and detection program Navigator uses to detect objects from the LIDAR. These objects are used for obstacle avoidance and in missions for knowing where to move to achieve tasks. This system is a work in progress replacement to the navigator_lidar_oa package (aka Batcave).

PCODAR will eventuality be merged into mil_common, the WIP version is in uf-mil/mil_common#127

This issue is a "metaissue" to track what needs to be done to make PCODAR more correct / useful for competition and integrate it into the other parts of the software stack

* [x]  move navigator_lidar_oa to deprecated
* [x]  update launch files to use PCODAR instead of navigator_lidar_oa
* [ ]  update missions as needed
* [x]  Fixed ogrid alignment uf-mil/mil_common#128
* [ ]  Add a feature for errosion
* [ ]  Tune parameters like filtering, inflation, etc to perform well with navigator bags

**Comment by ironmig** [comment]
Self assigned as I will be working on some of these as well as they are very urgent and the rest of the missions success depends on it. Looking to implement decay/errosion this weekend

**Comment by ironmig** [comment]
Updates:

* Have not reproduced ogrid alignment issue, considering it solved
* found  major bug with adding new points, fixed
* Consider replacing our associator with the pcl one [found here](http://docs.pointclouds.org/trunk/classpcl_1_1_hough3_d_grouping.html)
* consider making program multi threaded after doing some performance testing (does it operate at the speed the pointclouds come in?)

**Comment by ironmig** [comment]
Now tracked on individual issues as a functional PCODAR is merged
